api_platform:
    collection:
        pagination:
            #si on veux laisser le client piloter lenombre de résultat
            maximum_items_per_page: 5
            #Global pagination limit if not limit is not provided by client
            items_per_page: 10
            page_parameter_name: page
            items_per_page_parameter_name: limit
    allow_plain_identifiers: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
